
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Branch name rules
      uses: deepakputhraya/action-branch-name@v1.0.0
      with:
        regex: '([a-z])+\/([a-z-])+' # Regex the branch should match. This example enforces grouping
        allowed_prefixes: 'build,chore,ci,docs,feat,fix,perf,refactor,changes,revert,style,test' # All branches should start with the given prefix
        ignore: master,develop # Ignore exactly matching branch names from convention
        min_length: 5 # Min length of the branch name
        max_length: 30 # Max length of the branch name
